---
linters:
  enable:
    - depguard
    - errcheck
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - loggercheck
    - misspell
    - revive
    - staticcheck
    - stylecheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - depguard
        - errcheck

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: sync/atomic
            desc: "Use go.uber.org/atomic instead of sync/atomic"
          - pkg: github.com/go-kit/kit/log
            desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
  errcheck:
    exclude-functions:
      - io.Copy
      - io.WriteString
      - (net/http.ResponseWriter).Write
      - (*net/http.Server).Shutdown
      - (github.com/go-kit/log.Logger).Log


